modified entities.md
ghga-de/docs.ghga.de pull request #20
Opened 2024-07-30 15:48 UTC by anandhi-iyappan

- Modified entities.md to the new model changes
- Deleted concepts.md
- Deleted modules.md
- Modified standards.md

2024-07-31 07:28 UTC, mauerk commented on user_docs/metadata/overview.md
> +The schema broadly differentiates the research and administrative aspects of the metadata model - the research metadata aims at maximising the reusability and FAIRness of the data while the administr
```suggestion
Classes in the schema can be grouped into **Research Metadata** and **Administrative Metadata** based on the information they capture. The **Research Metadata** aims at maximising the reusability and FAIRness of the data, while the **Administrative Metadata** focuses on managing the resources, such as creation or acquisition of the data, rights management, and disposition. The Research Metadata classes include *Individual*, *Biospcimen/Sample*, *Experiment*, *Experiment Method*, *Analysis* and *Analysis Method*. The Administrative Metadata captures *Dataset*, *Data Access Policy*, *Data Access Committee*, *Publication*, and *Study*.  

The model also differentiates between three file types:
- **Research Data File**: A file which results from the omics experiment, such as sequencing of a sample.
- **Process Data File**: A file that is generated as output from an analysis performed on a *Research Data File*, such as alignment or processing.
- **Supporting File**: A file that provides further information about an *Individual*, *Experiment Method* or *Analysis Method*. These could be unstructured protocols or structured information, such as Phenopackets or BioCompute Objects.
```

2024-07-31 07:30 UTC, mauerk commented on user_docs/metadata/standards.md
> -### **Minimum Information about a high-throughput Nucleotide Sequencing Experiment (MINSEQE)**
Can we restore this?

2024-07-31 09:05 UTC, mauerk requested changes
- please make sure that entity names are always in upper case and in italics ("*Experiment Method*" instead of "Experiment methods")
- the protocol entities are in singular ("Experiment Method" instead of "Experiment methods")
- abbreviations such as "ID" or "EGA" need to be upper case
- use double line breaks to generate new paragraphs to make the content more easily readbale, especially towards the end of the entities.md file
- deleted files also need to be deleted in the mkdocs.yaml page tree so they do not appear as 404 error in the generated page (run `mkdocs serve` in VS Code to view the page in your browser)
- the data dictionary needs to be updated

2024-08-05 12:17 UTC, sbilge commented on user_docs/metadata/standards.md
> -### **Minimum Information about a high-throughput Nucleotide Sequencing Experiment (MINSEQE)**
MINSEQE restored

2024-08-05 12:18 UTC, sbilge commented on user_docs/metadata/standards.md
>  ### **Systematic Nomenclature of Medicine Clinical Terms**
Systematic Nomenclature of Medicine Clinical Terms is removed

2024-08-05 13:13 UTC, mauerk requested changes

2024-08-05 13:13 UTC, mauerk commented on user_docs/metadata/entities.md
> +If the data submitters have additional information to provide about the individual, then they can make use of the Individual supporting file class which requires the following information -  file for
```suggestion
If the data submitters have additional information to provide about the *Individual*, then they can make use of the *Individual Supporting File* class which requires the following information -  file format, file name, dataset associated with this file as well as if the file is included as part of the submission. 
```

2024-08-05 13:13 UTC, mauerk commented on user_docs/metadata/entities.md
> +An *Experiment* is an investigation that consists of a coordinated set of actions and observations designed to generate data with the goal of verifying, falsifying, or establishing the validity of a
```suggestion
An *Experiment* is an investigation that consists of a coordinated set of actions and observations designed to generate data with the goal of verifying, falsifying, or establishing the validity of a hypothesis. The *Experiment* entity describes the experimental setup or a protocol used for performing an omics experiment. 
```

2024-08-05 13:13 UTC, mauerk commented on user_docs/metadata/entities.md
> +The *Experiment* entity is linked to the *Sample* which implies one or more samples associated with this Experiment and the *Experimental Method* which implies one or more Experimental methods associ
```suggestion
The *Experiment* entity is linked to the *Sample* which implies one or more samples associated with this Experiment and the *Experiment Method* which implies one or more experiment methods associated with this Experiment. The outcome of an *Experiment* results in *Research Data File*.
```

2024-08-05 13:13 UTC, mauerk commented on user_docs/metadata/entities.md
> +### **Analysis Methods**
```suggestion
### **Analysis Method**
```

2024-08-05 13:13 UTC, mauerk commented on user_docs/metadata/entities.md
> +For any additional information pertaining to the *Analysis Methods* entity, the data submitter can use the *Analysis Method Supporting File*.
```suggestion
For any additional information pertaining to the *Analysis Method* entity, the data submitter can use the *Analysis Method Supporting File*.
```

2024-08-05 13:17 UTC, mauerk approved these changes

2024-08-05 13:20 UTC, merged